name: GitHub organization invitation request
description: Issue template for requesting an invitation to a GitHub organization.

title: "[GitHub organization invitation request] "

labels:
  - invitation
  - request

body:
  - type: markdown
    attributes:
      value: |
        <br/>
        Welcome! Please fill in the form below to request an invitation to the GitHub organization.

  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      options:
        - GitHub organization invitation request
    validations:
      required: true

  - type: dropdown
    id: organization
    attributes:
      label: Organization
      options:
        - devrel-kr
    validations:
      required: true

  - type: input
    id: github-handle
    attributes:
      label: GitHub Handle
      description: Enter your GitHub username without the `@` symbol.
      placeholder: octocat
    validations:
      required: true

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Confirmation
      options:
        - label: The GitHub handle I entered is my own account.
          required: true

  - type: markdown
    attributes:
      value: |
        <br/>
        When you submit the request, GitHub will send the organization invitation to your account and registered email address. After accepting the invitation, you can join the organization.
