name: GitHub 조직 초대 요청
description: GitHub 조직에 초대를 요청하기 위한 이슈 템플릿입니다.

title: "[GitHub 조직 초대 요청] "

labels:
  - invitation
  - request

body:
  - type: markdown
    attributes:
      value: |
        <br/>
        환영합니다! GitHub 조직에 초대를 요청하기 위해 아래 양식을 작성해주세요.

  - type: dropdown
    id: request-type
    attributes:
      label: 요청 유형
      options:
        - GitHub 조직 초대 요청
    validations:
      required: true

  - type: dropdown
    id: organization
    attributes:
      label: 조직
      options:
        - devrel-kr
    validations:
      required: true

  - type: input
    id: github-handle
    attributes:
      label: GitHub 핸들
      description: 이슈를 작성하는 본인의 GitHub 계정 이름을 `@` 없이 입력해 주세요.
      placeholder: octocat
    validations:
      required: true

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: 확인 사항
      options:
        - label: 입력한 GitHub 핸들은 이슈를 작성하는 본인의 계정입니다.
          required: true

  - type: markdown
    attributes:
      value: |
        <br/>
        초대 요청을 제출하면 GitHub 알림과 계정에 등록된 이메일로 조직 초대가 발송됩니다. 초대를 수락하면 조직에 참여할 수 있습니다. 감사합니다!
