name: Azure subscription onboarding request

description: Issue template for requesting onboarding to an Azure subscription.

title: "[Azure subscription onboarding request] "

labels:
  - onboarding
  - request

body:
  - type: markdown
    attributes:
      value: |
        <br/>
        Welcome! Please complete the form below to request Azure subscription onboarding.

  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      options:
        - Azure subscription onboarding request
    validations:
      required: true

  - type: dropdown
    id: organization
    attributes:
      label: Organization
      options:
        - {{ENTRA_TENANT_DOMAIN_NAME}}
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Jane Developer
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email
      placeholder: "jane.developer@gmail.com (use a personal email address like gmail.com, outlook.com, hotmail.com or so; work email is not allowed)"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br/>
        When the onboarding workflow processes your request, Azure will email the address you provide a link to join the subscription. Open the link and complete the steps to get access. Thank you!
