name: "Workflow: User Invitation to GitHub Organization"

on:
  issues:
    types:
      - opened
  workflow_dispatch:
    inputs:
      issue-number:
        description: "Issue number"
        required: true

permissions:
  contents: read
  issues: write

jobs:
  invite_user:
    name: "Invite User to GitHub Organization"

    if: |
      github.event_name == 'workflow_dispatch' ||
      startsWith(github.event.issue.title, '[GitHub 조직 초대 요청]')

    runs-on: ubuntu-latest

    steps:
      - name: Generate bot token
        id: bot-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: invitation
          permission-contents: read
          permission-issues: write
          permission-members: write

      - name: Check event payload - from issue
        if: |
          github.event_name != 'workflow_dispatch'
        shell: pwsh
        env:
          ISSUE_PAYLOAD: ${{ toJson(github.event.issue) }}
        run: |
          $env:ISSUE_PAYLOAD |
            Out-File -FilePath "${{ github.workspace }}/payload.json" -Encoding utf8 -Force

      - name: Check event payload - from workflow_dispatch
        if: |
          github.event_name == 'workflow_dispatch'
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          gh api "/repos/${{ github.repository }}/issues/${{ github.event.inputs.issue-number }}" |
            Out-File -FilePath "${{ github.workspace }}/payload.json" -Encoding utf8 -Force

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate GitHub organization request
        shell: pwsh
        run: |
          ./scripts/Test-GitHubInvitationRequest.ps1 `
            -InputFile "${{ github.workspace }}/payload.json" `
            -OutputFile "${{ github.workspace }}/issue.json" `
            -DueDate "${{ vars.INVITATION_DUE_DATE }}" `
            -Organization "devrel-kr"

      - name: Check validation result
        id: issue
        shell: pwsh
        run: |
          $result = Get-Content "${{ github.workspace }}/issue.json" -Raw | ConvertFrom-Json
          $tzi = [TimeZoneInfo]::FindSystemTimeZoneById("Asia/Seoul")

          echo "issueNumber=$($result.number)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          echo "submittedAt=$([TimeZoneInfo]::ConvertTime($result.createdAt, $tzi).ToString("yyyy-MM-dd HH:mm:ss.fff") + " +09:00")" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          echo "dueBy=$([TimeZoneInfo]::ConvertTime($result.dueDate, $tzi).ToString("yyyy-MM-dd HH:mm:ss.fff") + " +09:00")" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          echo "isValid=$($result.isValid)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          echo "invalidReasons=$('<ul><li> ' + $($result.invalidReasons -join '</li><li> ') + '</li></ul>')" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          echo "org=$($result.body.organisation)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          echo "githubHandle=$($result.body.githubHandle)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Comment to issue - Acknowledge
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ steps.bot-token.outputs.token }}
          issue-number: ${{ steps.issue.outputs.issueNumber }}
          emoji: "+1,rocket"
          body: |
            👋🏼 @${{ steps.issue.outputs.githubHandle }} 님!

            생성하신 GitHub 조직 초대 요청을 확인하고 있습니다.

      - name: Add label - Invalid
        if: |
          steps.issue.outputs.isValid == 'false'
        shell: bash
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          gh issue edit ${{ steps.issue.outputs.issueNumber }} \
            --add-label "invalid" \
            -R ${{ github.event.repository.full_name }}

      - name: Comment to issue - Invalid
        if: |
          steps.issue.outputs.isValid == 'false'
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ steps.bot-token.outputs.token }}
          issue-number: ${{ steps.issue.outputs.issueNumber }}
          body: |
            👋🏼 @${{ steps.issue.outputs.githubHandle }} 님!

            - 요청 시각: ${{ steps.issue.outputs.submittedAt }}
            - 요청 마감 시각: ${{ steps.issue.outputs.dueBy }}

            제출하신 GitHub 조직 초대 요청은 다음과 같은 이유로 유효하지 않습니다. 😢

            ${{ steps.issue.outputs.invalidReasons }}

      - name: Close issue - Invalid
        if: |
          steps.issue.outputs.isValid == 'false'
        shell: bash
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          gh issue close ${{ steps.issue.outputs.issueNumber }} \
            -c "제출한 요청이 유효하지 않습니다. 이슈를 닫습니다." \
            -R ${{ github.event.repository.full_name }}

      - name: Invite user to GitHub organization
        if: |
          steps.issue.outputs.isValid == 'true'
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          ./scripts/Invite-ToGitHubOrg.ps1 `
            -Organization "${{ steps.issue.outputs.org }}" `
            -GitHubHandle "${{ steps.issue.outputs.githubHandle }}"

      - name: Add label - Complete
        if: |
          steps.issue.outputs.isValid == 'true'
        shell: bash
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          gh issue edit ${{ steps.issue.outputs.issueNumber }} \
            --add-label "complete" \
            -R ${{ github.event.repository.full_name }}

      - name: Remove label - request
        if: |
          steps.issue.outputs.isValid == 'true'
        shell: bash
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          gh issue edit ${{ steps.issue.outputs.issueNumber }} \
            --remove-label "request" \
            -R ${{ github.event.repository.full_name }}

      - name: Comment to issue - Complete
        if: |
          steps.issue.outputs.isValid == 'true'
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ steps.bot-token.outputs.token }}
          issue-number: ${{ steps.issue.outputs.issueNumber }}
          emoji: "+1,rocket"
          body: |
            👋🏼 @${{ steps.issue.outputs.githubHandle }}님!

            GitHub 조직 초대를 발송했습니다. 초대를 수락하면 조직에 참여할 수 있습니다. 감사합니다!

      - name: Close issue - Complete
        if: |
          steps.issue.outputs.isValid == 'true'
        shell: bash
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          gh issue close ${{ steps.issue.outputs.issueNumber }} \
            -c "GitHub 조직 초대 요청을 완료했습니다. 이슈를 닫습니다." \
            -R ${{ github.event.repository.full_name }}
